### ISSUE TITLE
Add message handling for Console Service messages

### ISSUE THREAD

**Issue by bgrins** [bgrins/console-output-experiment#12]
If you open `data:text/html,<script>asdf</script>` you'll see a page error.  This doesn't come through the console API, but rather as a console service message.

Over RDP it looks like this:

    {
        "from" : "server1.conn2.child1/consoleActor2",
        "pageError" : { "category" : "HTML parser",
            "columnNumber" : 0,
            "error" : false,
            "errorMessage" : "The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.",
            "exception" : false,
            "info" : false,
            "lineNumber" : 0,
            "lineText" : "",
            "private" : false,
            "sourceName" : "data:text/html,<script>foadsfd</script>",
            "stacktrace" : null,
            "strict" : false,
            "timeStamp" : 1455666538128,
            "warning" : false
          },
        "type" : "pageError"
    },

Then in the frontend, something like this:

    <div xmlns="http://www.w3.org/1999/xhtml" id="console-msg-3" class="message" category="exception" severity="error" filter="exception">
     <span class="timestamp devtools-monospace">10:48:37.440 </span>
     <span class="indent" style="width: 0px;"></span>
     <span class="icon" title="Error"></span>
     <span class="message-body-wrapper message-body devtools-monospace"><span>The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.</span></span>
     <span value="1" class="message-repeats">1</span>
     <a href="data:text/html,&lt;script&gt;asdf&lt;/script&gt;" draggable="false" title="data:text/html,&lt;script&gt;asdf&lt;/script&gt;" class="message-location theme-link devtools-monospace"><span class="filename"> script&gt;</span></a> 
    </div>

**Comment by bgrins** [comment]
The current frontend handles this in `reportPageError` which instantiates a `Messages.Simple`

**Comment by linclark** [comment]
This was fixed via #13
